source_dir: src
config_path: "src/bashly.yml"
target_dir: build
lib_dir: lib
commands_dir: commands
strict: false
tab_indent: true
compact_short_flags: true
env: development
partials_extension: sh
conjoined_flag_args: true
show_examples_on_error: true
usage_colors:
  caption: underlined
  command: green
  arg: magenta
  flag: blue
  environment_variable: cyan
