#!/usr/bin/env bash

set_download_data() {
	local file_name response api_url release_tag release_download
	local -n ptr_tag=${1}
	local -n ptr_download_url=${2}

	api_url="https://api.github.com/repos/${repo}/releases"

	if [ "$tag" = "latest" ]; then
		api_url+="/latest"
		response=$(curl -fsSL "$api_url")
		release_tag=$(jq -r '.tag_name' <<<"$response")
		file_name="${pkgname}-${release_tag}.${file_ext}"
		release_download=$(jq --arg file_name "$file_name" -r '.assets[] | select(.browser_download_url | contains($file_name)) | .browser_download_url' <<<"$response")
	else
		file_name="${pkgname}-${release_tag}.${file_ext}"
		response=$(curl -fsSL "$api_url")
		release_download=$(jq --arg release_tag "$release_tag" --arg file_name "$file_name" -r '.[] | select(.tag_name == $release_tag) | .assets[] | select(.browser_download_url | contains($file_name)) | .browser_download_url' <<<"$response")
	fi

	[ -z "$release_download" ] && throw "No download URL found for tag $(yellow_bold "$release_tag")"

	# shellcheck disable=SC2034
	ptr_tag="$release_tag"
	# shellcheck disable=SC2034
	ptr_download_url="$release_download"
}

install() {
	local download_url workdir zipfile command

	download_url=$1
	workdir=$2
	zipfile=$3
	command="$pkgname self create"

	sudo mkdir -p "$workdir"
	sudo chmod -R 777 "$workdir"
	trap 'sudo rm -rf $workdir' EXIT

	sudo curl -fsSL "$download_url" -o "$zipfile"
	sudo unzip -q "$zipfile" -d "$install_dir/"

	if [ -n "$chroot_dir" ]; then
		command+=" --chroot $chroot_dir"
	fi

	$command
}

show_help() {
	cat <<EOF

$(bold Usage:)
  $(green_bold "$0") [$(blue options)]

$(bold Options:)
  $(blue -S ", " "-t --tag") $(yellow "<TAG>")
  	Specify the tag to download
	Available: latest, v1.0.0, v0.0.2, ...
	Default: $(magenta "latest")

  $(blue -S ", " "-d --dir") $(yellow "<DIR>")
	Specify the installation directory
	Default: $(magenta "/usr/local/bin")
	(NOTE: I don't recommend changing this as it causes bugs when used with chroot/arch-chroot)

  $(blue -S ", " "-c --chroot") $(yellow "<DIR>")
	Root directory for installation, used for chroot installations
	Default: $(magenta "None")
	NOTE: If this is set to '/mnt' and --dir is '/usr/local/bin', the final installation path will be '/mnt/usr/local/bin'

  $(blue -S ", " "-r --rmdeps")
	Remove build dependencies after installation
	Default: $(magenta "false")
	NOTE: Not removing build dependencies will make future updates faster

  $(blue -S ", " "-q --quiet")
	Quiet mode (no output)
	Default: $(magenta "false")
	NOTE: This will still print errors if any occur

  $(blue -S ", " "--dry-run")
	Don't actually install anything
	Default: $(magenta "false")

  $(blue -S ", " "-h --help")
	Show this help message and exit

$(bold Examples:)
  $(green_bold "$0")
	Installs the latest version of $pkgname in /usr/local/bin

  $(green_bold "$0") $(blue -S ", " "--chroot") $(yellow "/mnt")
	Installs the latest version of $pkgname in /mnt/usr/local/bin

  $(green_bold "$0") $(blue -S ", " "-t") v1.0.0
	Installs $pkgname v1.0.0 in /usr/local/bin
EOF
}

parse_args() {
	if [[ "$*" =~ -t|--tag ]]; then
		set -- "$@" --tag $tag
	fi

	while test $# -gt 0; do
		case $1 in
		-t | --tag)
			is_valid_tag "$2" || throw "Invalid tag format: $2" echo
			tag="$2"
			shift
			;;
		-d | --dir)
			dir_exists "$2" || throw "Invalid directory: $2" echo
			install_dir="$2"
			shift
			;;
		-c | --chroot)
			dir_exists "$2" || throw "Invalid chroot directory: $2" echo
			install_dir="${2}${install_dir}"
			chroot_dir="$2"
			shift
			;;
		-r | --rmdeps)
			rmdeps=true
			;;
		-q | --quiet)
			quiet=true
			;;
		--dry-run)
			dry_run=true
			;;
		-h | --help)
			show_help
			exit
			;;
		esac
		shift
	done
}

init() {
	#shellcheck source=utils
	source scripts/utils

	set -e
	clear

	need arch-install-scripts
	need git
	need mold
	need -b unzip
	need -b jq
	need -b curl
	install_dependencies

	# install options
	tag="latest"
	install_dir="/usr/local/bin"

	# internal use
	pkgname="aurbuilder"
	repo="sirius-red/${pkgname}"
	file_ext="zip"
	chroot_dir=

	parse_args "$@"
}

run() {
	local workdir zipfile download_url download_tag

	workdir="/tmp/${pkgname}-$$"
	zipfile="${workdir}/$pkgname.${file_ext}"

	set_download_data download_tag download_url

	if [ "$tag" == "latest" ]; then
		download_tag+=" $(green_bold "(latest)")"
	elif [[ "$tag" =~ -dev$ ]]; then
		download_tag+=" $(yellow_bold "(unstable)")"
	fi

	print
	print "$(magenta_bold "$(upper "$pkgname installer")")"
	print
	print "Version: $(blue_bold "$download_tag")"
	print "Repo: $(blue_bold $repo)"
	print "Download url: $(blue_bold "$download_url")"
	print "Install dir: $(blue_bold "$install_dir")"
	print

	dry_run || install "$download_url" "$workdir" "$zipfile"

	[ -z "$rmdeps" ] || remove_dependencies --dev
}

if init "$@" && run; then
	green_bold "Done!"
else
	red_bold "An error occurred!"
fi
